<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>

<% 
Class.forName("com.mysql.jdbc.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://dbproject.cvguwph9zu1e.us-east-2.rds.amazonaws.com:3306/AirlineFlight","admin", "Thomert1!");
Statement st = con.createStatement();
int filter = -1;
int flight=-1;
String accname = "";
String airID = "";
String revenue = "";
try{
	
	filter = Integer.parseInt(request.getParameter("filter"));
	if(filter==1){
		
		flight = Integer.parseInt(request.getParameter("data"));
		ResultSet rs = st.executeQuery("SELECT SUM(Booking_fee) AS total FROM AirlineFlight.Ticket NATURAL JOIN AirlineFlight.Associated where sold='Y' AND Flight="+flight);
		while(rs.next()){
			revenue = rs.getString(1);
		}
		if(revenue!=null){
			out.println("Revenue for flight #"+flight+"  is:         $"+revenue);
			out.println("<form action='admin.jsp'><input type='submit' value='Return'/></form>");
		}else{
			out.println("No revenue generated for flight #"+flight+"           or flight does not exist");
			out.println("<form action='admin.jsp'><input type='submit' value='Return'/></form>");
		}
		
	}else if(filter==2){
		
		airID = request.getParameter("data");
		ResultSet rs = st.executeQuery("SELECT SUM(Booking_fee) AS total FROM AirlineFlight.Ticket NATURAL JOIN AirlineFlight.Associated NATURAL JOIN AirlineFlight.Flight WHERE 2letterID='"+airID+"' AND sold='Y'");
		while(rs.next()){
			revenue = rs.getString(1);
		}
		if(revenue!=null){
			out.println("Revenue for Airline with ID: "+airID+"  is:         $"+revenue);
			out.println("<form action='admin.jsp'><input type='submit' value='Return'/></form>");
		}else{
			out.println("No revenue generated for Airline with ID: "+airID+"           or airline does not exist");
			out.println("<form action='admin.jsp'><input type='submit' value='Return'/></form>");
		}
		
	}else{
		
		accname = request.getParameter("data");
		ResultSet rs = st.executeQuery("SELECT SUM(Booking_fee) AS total FROM AirlineFlight.Ticket NATURAL JOIN AirlineFlight.Associated NATURAL JOIN AirlineFlight.Reservation WHERE accountname='"+accname+"' AND sold='Y'");
		while(rs.next()){
			revenue = rs.getString(1);
		}
		if(revenue!=null){
			out.println("Revenue generated by "+accname+"  is:         $"+revenue);
			out.println("<form action='admin.jsp'><input type='submit' value='Return'/></form>");
		}else{
			out.println("No revenue generated by "+accname+"           or customer account does not exist");
			out.println("<form action='admin.jsp'><input type='submit' value='Return'/></form>");
		}	
	}
	
}catch(Exception e){
	out.println("Error obtaining revenue");
	out.println("<form action='admin.jsp'><input type='submit' value='Return'/></form>");
}



%>
